/* ISM Coach v2 — professional goals, explainable recommendations and skill snapshot. */
(function(){
 const GOALS={meetings:{label:'Liderar reuniões',mods:[2,3,4,5,6]},presentations:{label:'Apresentar com confiança',mods:[7,8,9,10]},influence:{label:'Liderar e influenciar',mods:[11,12]},foundation:{label:'Fortalecer comunicação profissional',mods:[1,2,3]}};
 function obj(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
 function getGoal(){try{return localStorage.getItem('ismbe:goal')||'meetings'}catch{return 'meetings'}}
 function setGoal(g){if(!GOALS[g])return;try{localStorage.setItem('ismbe:goal',g)}catch{}render()}
 function lessons(){return obj(window.state?.lessons)}
 function pct(){const done=Object.values(lessons()).filter(v=>v==='mastered'||v==='done').length;return Math.min(100,Math.round(done/98*100))}
 function goalProgress(){const goal=GOALS[getGoal()],ls=lessons(),ids=[];goal.mods.forEach(m=>{const count=(window.COUNTS&&window.COUNTS[m])||0;for(let i=1;i<=count;i++)ids.push(`${m}.${i}`)});if(!ids.length)return 0;return Math.round(ids.filter(id=>ls[id]==='mastered'||ls[id]==='done').length/ids.length*100)}
 function lowLesson(){const scores=obj(window.state?.lessonScores),goal=GOALS[getGoal()];return Object.entries(scores).filter(([id])=>{const m=+id.split('.')[0];return /^\d+\.\d+$/.test(id)&&goal.mods.includes(m)}).sort((a,b)=>(+a[1]||0)-(+b[1]||0))[0]||null}
 function reviewDueCount(){const meta=obj(window.state?.reviewHistory),now=Date.now();return Object.values(meta).filter(x=>{if(!x?.last)return false;const days=Math.max(1,+x.nextDays||1);return now-Date.parse(x.last)>=days*86400000}).length}
 function skillSnapshot(){const s=obj(window.state?.skills),ex=obj(window.state?.exerciseResults);const vals=Object.values(ex).map(x=>+x?.score||0).filter(Boolean);const practice=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0;const speaking=Object.keys(obj(window.state?.speakingDone)).length;return{practice,speaking,review:Object.keys(obj(window.state?.reviewHistory)).length}}
 function recommendation(){const due=reviewDueCount(),weak=lowLesson(),progress=pct(),goal=GOALS[getGoal()];if(due>0)return{kind:'review',ey:'ISM COACH · REVISÃO',title:`Você tem ${due} ${due===1?'revisão pronta':'revisões prontas'}`,text:'Uma sessão curta agora ajuda a recuperar expressões antes que sejam esquecidas.',why:'Recomendado porque há conteúdo no prazo de revisão.',time:'≈ 5 min',label:'REVISAR AGORA →',action:'startSmartReview()'};if(weak&&(+weak[1]||0)<70)return{kind:'practice',ey:'ISM COACH · REFORÇO',title:`Reforce a lição ${weak[0]} para ${goal.label.toLowerCase()}`,text:'Seu histórico indica que este conteúdo merece mais uma recuperação ativa.',why:`Recomendado porque esta lição está entre os menores desempenhos do seu objetivo.`,time:'≈ 6 min',label:'CONTINUAR PRÁTICA →',action:'continueLearning()'};if(progress>=75)return{kind:'simulate',ey:'ISM COACH · APLICAÇÃO',title:'Transforme conhecimento em desempenho',text:`Seu avanço permite aplicar ${goal.label.toLowerCase()} em uma situação profissional completa.`,why:'Recomendado porque você já avançou o suficiente para priorizar aplicação.',time:'≈ 8 min',label:'TREINAR SITUAÇÃO →',action:"setNav('simulate');show('simulate');renderSimulation()"};return{kind:'continue',ey:'ISM COACH · PRÓXIMO PASSO',title:`Avance no objetivo: ${goal.label}`,text:'Retome exatamente do ponto em que parou e avance em uma sessão curta.',why:'Recomendado para manter continuidade e frequência de estudo.',time:'≈ 8 min',label:'CONTINUAR →',action:'continueLearning()'}}
 function greeting(){const h=new Date().getHours();return h<12?'Bom dia':h<18?'Boa tarde':'Boa noite'}
 function goalOptions(){const active=getGoal();return Object.entries(GOALS).map(([k,v])=>`<button class="coach-goal ${k===active?'on':''}" onclick="ISMCoach.setGoal('${k}')">${v.label}</button>`).join('')}
 function render(){const host=document.getElementById('ismCoach');if(!host)return;const r=recommendation(),g=GOALS[getGoal()],gp=goalProgress(),sk=skillSnapshot();host.className='ism-coach '+r.kind;host.innerHTML=`<div class="coach-top"><div><span class="ey">${r.ey}</span><h2>${greeting()}. O que vale fazer agora?</h2></div><span class="coach-time">${r.time}</span></div><div class="coach-goal-head"><span>SEU OBJETIVO</span><strong>${g.label}</strong><small>${gp}% do caminho relacionado concluído</small></div><div class="coach-goals" aria-label="Escolher objetivo profissional">${goalOptions()}</div><strong class="coach-title">${r.title}</strong><p>${r.text}</p><div class="coach-why">${r.why}</div><button class="btn coach-action" onclick="${r.action}">${r.label}</button><div class="coach-skills"><div><b>${sk.practice}%</b><span>Prática</span></div><div><b>${sk.speaking}</b><span>Speaking</span></div><div><b>${sk.review}</b><span>Revisões</span></div></div>`}
 window.ISMCoach={render,recommendation,setGoal,getGoal,goalProgress};
 window.addEventListener('load',()=>setTimeout(render,0));
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});
})();
