(()=>{'use strict';
const units=window.ISM_EXTRA_UNITS,key='ismbe:extra-practice:v1',view=document.getElementById('practice-view');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records={};try{const value=JSON.parse(localStorage.getItem(key)||'{}');if(value&&typeof value==='object'&&!Array.isArray(value))records=value;}catch{document.getElementById('storage-status').textContent='Não foi possível recuperar a prática adicional. O progresso Core e Premium não foi alterado.';}
let active=null;
function save(){try{localStorage.setItem(key,JSON.stringify(records));}catch{document.getElementById('storage-status').textContent='Este navegador não conseguiu salvar. Mantenha a página aberta e copie suas respostas antes de sair.';}}
function state(u){if(!records[u.id]||typeof records[u.id]!=='object')records[u.id]={};const s=records[u.id];s.answers=s.answers||{};s.checked=s.checked||{};s.drafts=s.drafts||{};s.order=Array.isArray(s.order)&&s.order.length===u.order[1].length?s.order:u.order[1].map((_,i)=>(i+1)%u.order[1].length);return s;}
const due=s=>s.nextReview&&Date.now()>=s.nextReview;
function catalog(){active=null;view.innerHTML='<h1>Mais prática, no seu ritmo</h1><p>Comece pelo módulo 1 ou escolha um desafio de entrevistas e dados. Você pode consultar as palavras, praticar e voltar depois para tentar lembrar sem o modelo.</p><p class="muted">Estas atividades são complementares. Têm registro próprio neste navegador e não mudam suas estrelas nem as conclusões do Core e Premium. As respostas escritas e orais usam autoavaliação guiada.</p><div class="library">'+units.map(u=>{const s=state(u);return '<article class="card '+(due(s)?'review-due':'')+'"><div class="ey">'+esc(u.group)+'</div><h2>'+esc(u.title)+'</h2><p>4 itens de vocabulário · 4 frases · 5 exercícios · desafio oral</p><p>'+ (due(s)?'Revisão disponível: tente responder sem consultar.':s.completed?'Prática registrada. Próxima revisão: '+new Date(s.nextReview).toLocaleDateString('pt-BR'): 'Primeira prática: cerca de 12–18 minutos; ajuste ao seu ritmo.')+'</p><a class="btn soft" href="#'+esc(u.id)+'">'+(s.completed?'Reabrir':'Começar')+' →</a></article>';}).join('')+'</div>';}
function audioButton(text,label='▶ Ouvir'){return '<button class="audio" type="button" data-audio="'+esc(text)+'">'+label+'</button>';}
function options(q,name,s){const offset=active.id.split('').reduce((a,c)=>a+c.charCodeAt(0),0)%q[1].length;return q[1].map((_,i)=>{const n=(i+offset)%q[1].length;return '<label><input type="radio" name="'+name+'" value="'+n+'" '+(String(s.answers[name])===String(n)?'checked':'')+'>'+esc(q[1][n])+'</label>';}).join('');}
function chart(c){const max=c.max||Math.max(...c.rows.map(r=>r[1]));return '<section class="card"><h2>'+esc(c.title)+'</h2><p>Unidade: '+esc(c.unit)+'. Consulte o gráfico e a tabela equivalente.</p><div role="img" aria-label="'+esc(c.title+'. '+c.rows.map(r=>r[0]+': '+r[1]+' '+c.unit).join('; '))+'">'+c.rows.map(r=>'<div class="chart-row" aria-hidden="true"><span>'+esc(r[0])+'</span><div class="chart-track"><div class="chart-bar" style="width:'+r[1]/max*100+'%"></div></div><b>'+r[1]+'</b></div>').join('')+'</div><table><caption>Valores utilizados nas atividades ('+esc(c.unit)+')</caption><thead><tr><th scope="col">Categoria</th><th scope="col">Valor</th></tr></thead><tbody>'+c.rows.map(r=>'<tr><th scope="row">'+esc(r[0])+'</th><td>'+r[1]+'</td></tr>').join('')+'</tbody></table></section>';}
function renderOrder(){const u=active,s=state(u);document.getElementById('order-list').innerHTML=s.order.map((n,i)=>'<li>'+esc(u.order[1][n])+'<div><button class="mini" type="button" data-move="'+i+'" data-direction="-1" aria-label="Mover trecho '+(i+1)+' para cima" '+(i===0?'disabled':'')+'>↑</button><button class="mini" type="button" data-move="'+i+'" data-direction="1" aria-label="Mover trecho '+(i+1)+' para baixo" '+(i===s.order.length-1?'disabled':'')+'>↓</button></div></li>').join('');}
function renderUnit(u){active=u;const s=state(u);view.innerHTML='<div class="ey">'+esc(u.group)+'</div><h1>'+esc(u.title)+'</h1><p>Estude os exemplos e depois feche o material de apoio para praticar. Os modelos são sugestões: adapte-os ao seu trabalho.</p>'+(s.completed?'<p class="feedback">Você já registrou esta prática. '+(due(s)?'Sua revisão está disponível.':'Próxima revisão: '+new Date(s.nextReview).toLocaleDateString('pt-BR'))+'</p><button class="btn soft" data-review>Começar nova tentativa sem modelos</button>':'')+
 '<details class="card"><summary>Palavras, combinações e frases de apoio</summary><h2>Vocabulário em contexto</h2><div class="word-list">'+u.words.map(w=>'<div><strong>'+esc(w[0])+'</strong><p class="pt">'+esc(w[1])+'</p><p>'+esc(w[2])+'</p>'+audioButton(w[2])+'</div>').join('')+'</div><h2>Frases para usar</h2>'+u.phrases.map(p=>'<div class="phrase"><p class="en">'+esc(p[0])+'</p><p class="pt">'+esc(p[1])+'</p>'+audioButton(p[0])+audioButton(p[0],'Ouvir devagar').replace('data-audio=','data-slow="true" data-audio=')+'</div>').join('')+'</details>'+(u.chart?chart(u.chart):'')+
 '<fieldset class="practice-item"><legend>1 · Escolha pelo contexto</legend><p>'+esc(u.choice[0])+'</p>'+options([u.choice[0],u.choice[1]],'choice',s)+'<button class="btn soft" data-check="choice">Conferir resposta</button><p class="feedback" id="feedback-choice" role="status"></p></fieldset>'+
 '<fieldset class="practice-item"><legend>2 · Complete a combinação</legend><label for="gap">'+esc(u.gap[0])+'</label><input id="gap" type="text" data-draft="gap" autocomplete="off" value="'+esc(s.drafts.gap)+'"><button class="btn soft" data-check="gap">Conferir resposta</button><p class="feedback" id="feedback-gap" role="status"></p></fieldset>'+
 '<fieldset class="practice-item"><legend>3 · Organize a sequência</legend><p>'+esc(u.order[0])+'</p><ol id="order-list" class="order-list"></ol><button class="btn soft" data-check="order">Conferir sequência</button><p class="feedback" id="feedback-order" role="status"></p></fieldset>'+
 '<fieldset class="practice-item"><legend>4 · Ouça e compreenda</legend><p>'+esc(u.listen[1])+'</p>'+audioButton(u.listen[0])+options([u.listen[1],u.listen[2]],'listen',s)+'<button class="btn soft" data-check="listen">Conferir resposta</button><details class="transcript"><summary>Ver transcrição / alternativa sem áudio</summary><p>'+esc(u.listen[0])+'</p><p class="muted">Se consultar o texto, use esta atividade como compreensão de leitura.</p></details><p class="feedback" id="feedback-listen" role="status"></p></fieldset>'+
 '<fieldset class="practice-item"><legend>5 · Escreva sua resposta</legend><label for="writing">'+esc(u.write[0])+'</label><textarea id="writing" data-draft="writing">'+esc(s.drafts.writing)+'</textarea><button class="btn soft" data-check="writing">Comparar com modelo e critérios</button><div id="writing-model"></div><p class="feedback" id="feedback-writing" role="status"></p></fieldset>'+
 '<section class="card practice-item"><h2>Seu desafio oral</h2><p>'+esc(u.oral[0])+'</p><p class="muted">Pratique sem ler. Não há análise automática de pronúncia. Verifique os critérios abaixo com honestidade.</p><div class="checklist">'+u.oral[1].map((c,i)=>'<label><input type="checkbox" data-self="oral'+i+'" '+(s.checked['oral'+i]?'checked':'')+'>'+esc(c)+'</label>').join('')+'</div></section><div class="unit-actions"><button class="btn" data-finish>Registrar prática e programar revisão</button><p id="finish-status" role="status"></p></div>';
renderOrder();if(s.showModel)showModel();}
function showModel(){const u=active,s=state(u);document.getElementById('writing-model').innerHTML='<div class="model"><h3>Compare e melhore</h3><p>'+esc(u.write[1])+'</p>'+(u.model?'<h3>Resposta completa · exemplo fictício</h3><p>'+esc(u.model[0])+'</p>'+audioButton(u.model[0])+'<details><summary>Tradução de apoio</summary><p>'+esc(u.model[1])+'</p></details><h3>Por que o modelo funciona</h3><ul>'+u.comments.map(c=>'<li>'+esc(c)+'</li>').join('')+'</ul>':'')+'<p>Uma resposta diferente também pode funcionar. Revise seu texto antes de marcar os critérios.</p><div class="checklist">'+u.write[2].map((c,i)=>'<label><input type="checkbox" data-self="write'+i+'" '+(s.checked['write'+i]?'checked':'')+'>'+esc(c)+'</label>').join('')+'</div></div>';}
view.addEventListener('input',e=>{if(!active)return;const s=state(active),t=e.target;if(t.dataset.draft){s.drafts[t.dataset.draft]=t.value;if(t.dataset.draft==='gap'){s.checked.gap=false;document.getElementById('feedback-gap').textContent='Resposta alterada. Confira novamente.';}if(t.dataset.draft==='writing'){active.write[2].forEach((_,i)=>s.checked['write'+i]=false);view.querySelectorAll('[data-self^=write]').forEach(c=>c.checked=false);}}save();});
view.addEventListener('change',e=>{if(!active)return;const s=state(active),t=e.target;if(t.type==='radio'){s.answers[t.name]=Number(t.value);s.checked[t.name]=false;document.getElementById('feedback-'+t.name).textContent='Resposta alterada. Confira novamente.';}if(t.dataset.self)s.checked[t.dataset.self]=t.checked;save();});
view.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!active)return;const u=active,s=state(u);
if(b.dataset.audio){window.ISMAudio?.speak(b.dataset.audio,b.dataset.slow?0.72:0.95);return;}
if(b.hasAttribute('data-review')){if(!confirm('Começar uma nova tentativa? O registro de conclusão permanece; as respostas desta prática serão substituídas.'))return;records[u.id]={completed:s.completed,nextReview:s.nextReview,reviewCount:s.reviewCount,lastCompleted:s.lastCompleted};save();renderUnit(u);return;}
if(b.dataset.move!==undefined){const i=Number(b.dataset.move),j=i+Number(b.dataset.direction);[s.order[i],s.order[j]]=[s.order[j],s.order[i]];s.checked.order=false;save();renderOrder();return;}
if(b.dataset.check){const type=b.dataset.check,feedback=document.getElementById('feedback-'+type);let ok=false,explanation='';
if(type==='writing'){if(!(s.drafts.writing||'').trim()){feedback.textContent='Escreva sua tentativa antes de consultar o modelo.';return;}s.showModel=true;showModel();feedback.textContent='Compare sua resposta e marque os critérios que você cumpriu. Não há nota automática para o texto.';save();return;}
if(type==='choice'||type==='listen'){if(s.answers[type]===undefined){feedback.textContent='Escolha uma alternativa primeiro.';return;}const q=type==='choice'?u.choice:[u.listen[1],u.listen[2],u.listen[3],u.listen[4]];ok=s.answers[type]===q[2];explanation=q[3];}
if(type==='gap'){ok=u.gap[1].includes((s.drafts.gap||'').trim().toLowerCase().replace(/[.!?]+$/,''));explanation=u.gap[2]+(ok?'':' Resposta: '+u.gap[1].join(' / ')+'.');}
if(type==='order'){ok=s.order.every((n,i)=>n===i);explanation=ok?'A sequência apresenta o contexto, desenvolve a informação e fecha com continuidade.':'Tente novamente. Sequência de referência: '+u.order[1].join(' → ');}
s.checked[type]=ok;feedback.textContent=(ok?'Correto. ':'Revise. ')+explanation;save();return;}
if(b.hasAttribute('data-finish')){const status=document.getElementById('finish-status');if(!['choice','gap','order','listen'].every(k=>s.checked[k])||!(s.drafts.writing||'').trim()||!u.write[2].every((_,i)=>s.checked['write'+i])||!u.oral[1].every((_,i)=>s.checked['oral'+i])){status.textContent='Confira os quatro exercícios objetivos, escreva sua resposta e complete a autoavaliação escrita e oral antes de registrar.';return;}
if(!s.completed||due(s)){s.reviewCount=(s.reviewCount||0)+1;const days=[1,3,7,14][Math.min(s.reviewCount-1,3)];s.lastCompleted=Date.now();s.nextReview=Date.now()+days*86400000;}s.completed=true;save();status.textContent='Prática registrada. Próxima revisão: '+new Date(s.nextReview).toLocaleDateString('pt-BR')+'. Os intervalos são sugestões de estudo, não uma medição de domínio.';}
});
function route(){window.ISMAudio?.stop();const id=location.hash.slice(1),u=units.find(u=>u.id===id);if(u)renderUnit(u);else catalog();window.scrollTo(0,0);}
window.addEventListener('hashchange',route);route();
})();
