(()=>{'use strict';
 const courses=window.ISM_PREMIUM_COURSES,E=window.ISMPremiumEngine,view=document.getElementById('course-view'),states={};let active=null;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function state(c){if(!states[c.id]){const raw=ISMStorage.read(E.key(c.id));states[c.id]=E.obj(raw.lessons);}return states[c.id];}
 function current(){const {course:c,index:i}=active,id=E.lessonId(c,i),data=state(c);return data[id]=E.record(data[id]);}
 function save(c){return ISMStorage.write(E.key(c.id),{version:1,lessons:state(c)});}
 function audio(t){return '<button class="audio" data-audio="'+esc(t)+'">▶ Ouvir</button><button class="audio" data-audio="'+esc(t)+'" data-slow="1">Ouvir devagar</button>';}
 function progress(c){const n=E.count(c,state(c));return '<progress aria-label="Lições concluídas em '+esc(c.title)+'" value="'+n+'" max="'+c.lessons.length+'"></progress><p>'+n+' de '+c.lessons.length+' lições concluídas</p>';}
 function hub(){view.innerHTML='<div class="hero"><div class="ey">Premium · Comunicação e carreira</div><h1>Pratique para o seu próximo desafio.</h1><p>Escolha uma trilha. Estude as expressões, resolva os exercícios e aplique o que aprendeu em uma situação do seu trabalho.</p><p class="muted">Nível sugerido: intermediário em diante. As traduções e os modelos ajudam na preparação. Reserve cerca de 15–20 minutos por lição, ajustando ao seu ritmo.</p></div><div class="actions"><a class="btn soft" href="interview.html">P1 · Job Interviews</a><a class="btn soft" href="emails.html">P2 · Professional Writing</a></div><div class="grid">'+courses.map(c=>'<article class="card"><div class="ey">'+c.id+' · '+c.lessons.length+' lições</div><h2>'+esc(c.title)+'</h2><p class="pt">'+esc(c.pt)+'</p><p>'+esc(c.goal)+'</p>'+progress(c)+'<a class="btn soft" href="#'+c.id+'">Explorar trilha →</a></article>').join('')+'</div>';}
 function dashboard(c){const n=E.count(c,state(c)),next=c.lessons.findIndex((_,i)=>E.obj(state(c)[E.lessonId(c,i)]).done!==true);view.innerHTML='<a href="premium.html">← Todas as trilhas</a><div class="hero"><div class="ey">'+c.id+' · '+esc(c.pt)+'</div><h1>'+esc(c.title)+'</h1><p>'+esc(c.goal)+'</p>'+progress(c)+'<a class="btn" href="#'+c.id+'/'+(next<0?1:next+1)+'">'+(next<0?'Revisar lições':'Continuar estudando')+' →</a></div>'+(n===c.lessons.length?'<div class="card completion"><h2>Trilha concluída</h2><p>Você registrou todas as atividades. Escolha uma situação real para aplicar e revisite as lições conforme sua necessidade. Este registro não é uma certificação de proficiência.</p></div>':'')+'<p class="muted">Cada lição: contexto → linguagem → exercícios → aplicação → prática oral. As conclusões permanecem ao revisar.</p><ol class="lesson-list">'+c.lessons.map((l,i)=>{const done=E.obj(state(c)[E.lessonId(c,i)]).done;return '<li><a class="lesson-link '+(done?'done':'')+'" href="#'+c.id+'/'+(i+1)+'"><span class="num">'+(done?'✓':String(i+1).padStart(2,'0'))+'</span><span><b>'+esc(l[0])+'</b><small>'+esc(l[1])+' · '+(done?'Concluída':'15–20 min sugeridos')+'</small></span></a></li>';}).join('')+'</ol>';}
 function status(s,l){return [s.choiceCorrect?'✓ Escolha':'○ Escolha',s.gapCorrect?'✓ Expressão':'○ Expressão',s.model&&l[12].every((_,i)=>s.criteria[i])?'✓ Escrita':'○ Escrita',s.oral?'✓ Oral':'○ Oral',...(l[13]?.listening?[s.listeningCorrect?'✓ Compreensão':'○ Compreensão']:[])].join(' · ');}
 function lesson(c,i){const l=c.lessons[i],s=current();view.innerHTML='<div class="reading"><a href="#'+c.id+'">← '+esc(c.title)+'</a><div class="hero"><div class="ey">'+E.lessonId(c,i)+' · Lição '+(i+1)+' de '+c.lessons.length+'</div><h1>'+esc(l[0])+'</h1><p class="pt">'+esc(l[1])+'</p><p class="step-status" id="step-status">'+status(s,l)+'</p>'+(s.done?'<p>✓ Lição já concluída. Você pode revisar sem perder esse registro.</p>':'')+'</div><nav class="section-nav" aria-label="Etapas da lição">'+[['context','Contexto'],['language','Linguagem'],['exercises','Exercícios'],...(l[13]?.listening?[['listening','Compreensão']]:[]),['writing','Aplicar'],['oral','Praticar oralmente']].map(([id,title])=>'<a href="#'+c.id+'/'+(i+1)+'" data-section="'+id+'">'+title+'</a>').join('')+'</nav>'+
 '<section id="context" class="card"><div class="ey">1 · Contexto</div><h2>Seu desafio profissional</h2><p>'+esc(l[2])+'</p><p class="muted">Antes de continuar, pense: o que você precisa alcançar nesta conversa?</p></section>'+
 '<section id="language" class="card"><div class="ey">2 · Linguagem</div><h2>Palavras e expressões em contexto</h2><ul class="vocabulary">'+l[4].map(w=>{const [en,pt]=w.split('|');return '<li><b>'+esc(en)+'</b><span>'+esc(pt)+'</span></li>';}).join('')+'</ul>'+l[3].map((_,j)=>j).filter(j=>j%2===0).map(j=>'<div class="phrase"><p class="en" lang="en">'+esc(l[3][j])+'</p><p class="pt">'+esc(l[3][j+1])+'</p>'+audio(l[3][j])+'</div>').join('')+'<p class="muted">Ouça, repita e adapte. O áudio usa a voz em inglês disponível no seu navegador ou aparelho.</p></section>'+
 notes(l)+'<fieldset id="exercises"><legend>3 · Escolha pelo contexto</legend><p>'+esc(l[5])+'</p>'+E.order(l,i).map(n=>'<label class="option"><input type="radio" name="choice" value="'+n+'" '+(s.choice===n?'checked':'')+'><span>'+esc(l[6][n])+'</span></label>').join('')+'<button class="btn soft" data-check="choice">Conferir resposta</button><p id="choice-feedback" class="feedback" role="status">'+(s.choiceCorrect?'✓ Correto. '+esc(l[8]):'')+'</p></fieldset>'+
 '<fieldset><legend>4 · Complete a expressão</legend><p class="muted">Use a palavra da expressão estudada. Outras formulações também podem ser válidas.</p><label for="gap">'+esc(l[9][0])+'</label><input type="text" id="gap" autocomplete="off" value="'+esc(s.gap)+'"><button class="btn soft" data-check="gap">Conferir expressão</button><p id="gap-feedback" class="feedback" role="status">'+(s.gapCorrect?'✓ Correto. '+esc(l[9][2]):'')+'</p></fieldset>'+
 listening(l,s,i)+'<section id="writing" class="card"><div class="ey">5 · Aplicar ao trabalho</div><h2>Escreva sua resposta</h2><label for="draft">'+esc(l[10])+'</label><textarea id="draft" lang="en" placeholder="Escreva sua tentativa em inglês…">'+esc(s.draft)+'</textarea><p id="draft-status" class="muted" role="status">Seu rascunho é salvo neste navegador ao escrever.</p><button class="btn soft" data-model>Comparar com um modelo</button><div id="model-area">'+(s.model?model(l,s):'')+'</div></section>'+
 '<section id="oral" class="card"><div class="ey">6 · Praticar oralmente</div><h2>Agora, fale sem ler</h2><p>Use a situação desta lição. Fale por 30–60 segundos, ou alterne as falas com outra pessoa. Depois confira se sua mensagem atende aos critérios da atividade escrita. Repita se precisar.</p><label class="criterion"><input type="checkbox" data-oral '+(s.oral?'checked':'')+'><span>Pratiquei em voz alta sem ler o modelo e revisei minha clareza e o objetivo da mensagem.</span></label><p class="muted">Autoavaliação: o app não grava nem avalia automaticamente sua pronúncia.</p></section>'+
 '<section class="card"><button class="btn" data-finish>'+(s.done?'✓ Lição concluída':'Concluir lição')+'</button><p id="finish-status" class="feedback" role="status"></p><div class="actions">'+(i?'<a class="btn soft" href="#'+c.id+'/'+i+'">← Lição anterior</a>':'<a class="btn soft" href="#'+c.id+'">← Trilha</a>')+(i+1<c.lessons.length?'<a class="btn soft" href="#'+c.id+'/'+(i+2)+'">Próxima lição →</a>':'<a class="btn soft" href="#'+c.id+'">Ver progresso →</a>')+'</div></section></div>';}
 function notes(l){const m=l[13];if(!m?.notes?.length)return '';return '<section class="card"><h2>Entenda e use no trabalho</h2>'+m.notes.map(([title,body])=>'<h3>'+esc(title)+'</h3><p>'+esc(body)+'</p>').join('')+(m.sources.length?'<details><summary>Fontes e leitura complementar</summary><p class="muted">Referências consultadas para o conteúdo. Os diálogos e exercícios são exemplos autorais fictícios.</p><ul>'+m.sources.map(([name,url])=>'<li><a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(name)+' ↗</a></li>').join('')+'</ul></details>':'')+'</section>';}
 function listening(l,s,i){const q=l[13]?.listening;if(!q)return '';return '<fieldset id="listening"><legend>Compreensão de um diálogo</legend><p>Ouça antes de abrir a transcrição. Se usar o texto, pratique como compreensão de leitura.</p><p class="muted">Diálogo fictício lido por voz sintética do aparelho. Não é uma gravação de falantes reais nem uma representação de todos os sotaques de um país.</p>'+(q.required===false?'<p class="muted">Prática complementar: não altera os requisitos de conclusão desta lição.</p>':'')+audio(q.text)+'<details><summary>Ver transcrição</summary><p lang="en">'+esc(q.text)+'</p></details><h3>'+esc(q.question)+'</h3>'+q.options.map((_,j)=>(j+i+1)%q.options.length).map(n=>'<label class="option"><input type="radio" name="listening" value="'+n+'" '+(s.listening===n?'checked':'')+'><span>'+esc(q.options[n])+'</span></label>').join('')+'<button class="btn soft" data-check="listening">Conferir compreensão</button><p class="feedback" id="listening-feedback" role="status">'+(s.listeningCorrect?'✓ Correto. '+esc(q.feedback):'')+'</p></fieldset>';}
 function model(l,s){return '<div class="model"><h3>Exemplo de resposta</h3><p lang="en">'+esc(l[11])+'</p>'+audio(l[11])+'<p class="muted">Exemplo fictício, não uma resposta única. Adapte os detalhes à sua realidade.</p></div><h3>Compare e revise</h3><p>Confira os critérios abaixo. Sua marcação é uma autoavaliação; o app não corrige automaticamente a qualidade do texto.</p><div class="checklist">'+l[12].map((x,j)=>'<label class="criterion"><input type="checkbox" data-criterion="'+j+'" '+(s.criteria[j]?'checked':'')+'><span>'+esc(x)+'</span></label>').join('')+'</div>';}
 function updateSteps(){if(active?.index!==null&&active?.course){document.getElementById('step-status').textContent=status(current(),active.course.lessons[active.index]);}}
 view.addEventListener('input',e=>{if(!active?.course||active.index===null)return;const s=current(),l=active.course.lessons[active.index];if(e.target.id==='draft'){s.draft=e.target.value;s.criteria=[];s.oral=false;view.querySelectorAll('[data-criterion],[data-oral]').forEach(x=>x.checked=false);const ok=save(active.course);document.getElementById('draft-status').textContent=ok?'Rascunho salvo. Ao editar, confira novamente os critérios e a prática oral.':'Não foi possível salvar. Copie seu texto antes de sair.';}if(e.target.id==='gap'){s.gap=e.target.value;s.gapCorrect=false;document.getElementById('gap-feedback').textContent='Expressão alterada. Confira novamente.';save(active.course);}updateSteps();});
 view.addEventListener('change',e=>{if(!active?.course||active.index===null)return;const s=current(),t=e.target;if(t.name==='listening'){s.listening=Number(t.value);s.listeningCorrect=false;document.getElementById('listening-feedback').textContent='Alternativa alterada. Confira novamente.';}if(t.name==='choice'){s.choice=Number(t.value);s.choiceCorrect=false;document.getElementById('choice-feedback').textContent='Alternativa alterada. Confira novamente.';}if(t.hasAttribute('data-criterion'))s.criteria[Number(t.dataset.criterion)]=t.checked;if(t.hasAttribute('data-oral'))s.oral=t.checked;save(active.course);updateSteps();});
 view.addEventListener('click',e=>{const t=e.target.closest('button,[data-section]');if(!t||!active?.course||active.index===null)return;const c=active.course,l=c.lessons[active.index],s=current();if(t.dataset.section){e.preventDefault();const section=document.getElementById(t.dataset.section);section.tabIndex=-1;section.focus({preventScroll:true});section.scrollIntoView({block:'start'});return;}if(t.dataset.audio){window.ISMAudio?.speak(t.dataset.audio,t.dataset.slow?0.72:0.95);return;}if(t.dataset.check==='listening'){const q=l[13].listening,f=document.getElementById('listening-feedback');if(s.listening===null){f.textContent='Escolha uma alternativa primeiro.';return;}s.listeningCorrect=s.listening===q.answer;f.textContent=(s.listeningCorrect?'✓ Correto. ':'Revise e tente novamente. ')+q.feedback;save(c);updateSteps();return;}if(t.dataset.check==='choice'){const f=document.getElementById('choice-feedback');if(s.choice===null){f.textContent='Escolha uma alternativa primeiro.';return;}s.choiceCorrect=s.choice===l[7];f.textContent=(s.choiceCorrect?'✓ Correto. ':'Revise e escolha outra alternativa. ')+l[8];save(c);updateSteps();return;}if(t.dataset.check==='gap'){const f=document.getElementById('gap-feedback');if(!s.gap.trim()){f.textContent='Escreva a palavra que falta primeiro.';return;}s.gapCorrect=E.gapOK(s.gap,l);f.textContent=(s.gapCorrect?'✓ Correto. ':'Compare com a expressão estudada. Palavra esperada: '+l[9][1]+'. ')+l[9][2];save(c);updateSteps();return;}if(t.hasAttribute('data-model')){if(!s.draft.trim()){document.getElementById('draft-status').textContent='Escreva uma tentativa antes de abrir o modelo.';document.getElementById('draft').focus();return;}s.model=true;document.getElementById('model-area').innerHTML=model(l,s);save(c);return;}if(t.hasAttribute('data-finish')){const f=document.getElementById('finish-status');if(!E.ready(s,l)){f.textContent='Conclua os exercícios obrigatórios desta lição, escreva sua resposta, compare com o modelo e marque os critérios de escrita e a prática oral.';return;}const prior=s.done;s.done=true;if(!save(c)){s.done=prior;f.textContent='Não foi possível salvar a conclusão. Copie sua resposta e mantenha a página aberta.';return;}f.textContent='✓ Conclusão salva. Use Próxima lição ou Ver progresso para continuar.';t.textContent='✓ Lição concluída';}});
 function render(){window.ISMAudio?.stop();active=E.route(location.hash,courses);if(active.course&&active.index!==null)lesson(active.course,active.index);else if(active.course)dashboard(active.course);else hub();const heading=view.querySelector('h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}document.title=active.course?'ISM Premium — '+active.course.title:'ISM Premium — Trilhas profissionais';window.scrollTo(0,0);}
 document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();view.tabIndex=-1;view.focus();view.scrollIntoView({block:'start'});});window.addEventListener('hashchange',render);render();
})();
