'use strict';
const levels=['Elementary','Pre-Intermediate','Intermediate','Upper-Intermediate','Advanced'];
const interviews=[
{q:'Tell me about yourself.',a:'My name is Alex. I work in sales. I am organized and friendly.',task:'Introduce yourself, your role and one skill.'},
{q:'Why do you want this job?',a:'I enjoy working with customers. I have two years of experience, and I would like to develop my communication skills in an international team.',task:'Explain your motivation and one relevant experience.'},
{q:'Tell me about a challenge you solved at work.',a:'Our team missed a deadline because the requirements changed. I organized a short meeting, clarified priorities and redistributed tasks. We delivered the revised project on time.',task:'Answer using Situation → Action → Result.'},
{q:'How have you influenced stakeholders without formal authority?',a:'I aligned the team around a measurable goal, presented evidence of the expected benefit and invited objections early. We reached agreement and reduced processing time by 18%.',task:'Describe stakeholder alignment, evidence and measurable impact.'},
{q:'Describe a strategic decision you would reconsider.',a:'I once prioritized speed over stakeholder consultation. Although delivery was on schedule, adoption suffered. I later introduced an early validation stage; the experience taught me to balance execution risk with organizational buy-in.',task:'Explain trade-offs, accountability and lessons learned.'}
];
const emails=[
{subject:'Meeting time',from:'Hi Sam,\nCan we meet on Tuesday at 10?\nThanks,\nAlex',task:'Write a short, polite invitation with a date and time.',criteria:'Greeting, day, time and closing.'},
{subject:'Request for information',from:'Dear Ms Lee,\nCould you please send the updated price list by Thursday? We need it to prepare our proposal.\nBest regards,\nAlex',task:'Request a document politely and explain why you need it.',criteria:'Polite request, deadline, reason and closing.'},
{subject:'Project status update',from:'Hello team,\nWe have completed the design phase. Testing begins next Monday. The main risk is a delay in supplier approval; I will share a revised timeline on Friday.\nKind regards,\nAlex',task:'Send a status email including progress, a risk and the next action.',criteria:'Clear subject, progress, risk, action owner and timeline.'},
{subject:'Responding to a client concern',from:'Dear Jordan,\nThank you for raising your concerns about the revised schedule. I understand the impact on your team. We can prioritize the critical deliverables this week and review the remaining scope together on Monday.\nBest regards,\nAlex',task:'Respond diplomatically to a complaint and propose a workable solution.',criteria:'Empathy, precise issue, solution, next step and professional tone.'},
{subject:'Executive recommendation',from:'Dear leadership team,\nFollowing our review of the forecast, I recommend a phased launch rather than a full rollout. This approach reduces exposure while preserving our strategic objective. Subject to approval, I will circulate milestones and risk owners by Wednesday.\nSincerely,\nAlex',task:'Write a concise executive recommendation acknowledging uncertainty and proposing action.',criteria:'Decision, supporting rationale, qualified risk, ownership and deadline.'}
];
const chartData=[
{title:'Weekly orders',unit:'orders',labels:['Mon','Tue','Wed','Thu'],values:[12,18,15,22],task:'Describe the highest and lowest day.',model:'Orders were lowest on Monday at 12 and highest on Thursday at 22.'},
{title:'Monthly website visits',unit:'visits',labels:['Jan','Feb','Mar','Apr'],values:[120,150,170,200],task:'Describe the trend and compare January with April.',model:'Visits increased steadily from 120 in January to 200 in April.'},
{title:'Quarterly sales',unit:'$ thousands',labels:['Q1','Q2','Q3','Q4'],values:[42,56,51,72],task:'Explain the overall trend, the Q3 dip and the final result.',model:'Sales rose overall, despite a slight decline in Q3, and peaked at $72,000 in Q4.'},
{title:'Conversion by channel',unit:'percent',labels:['Web','Email','Ads','Partner'],values:[3,7,4,9],task:'Recommend which channel to prioritize and acknowledge one limitation.',model:'Partners have the highest conversion rate at 9%, but we should consider acquisition costs before reallocating budget.'},
{title:'Forecast scenarios',unit:'$ millions',labels:['Bear','Base','Bull'],values:[2.1,3.2,4.6],task:'Present a qualified recommendation, uncertainty and a mitigation plan.',model:'The base case projects $3.2 million, while downside exposure reaches $2.1 million. I recommend phased investment with quarterly checkpoints.'}
];
const key='ismbe:skills-studio:v1';let state={};try{state=JSON.parse(localStorage.getItem(key))||{}}catch{};const el=id=>document.getElementById(id);let mode=new URLSearchParams(location.search).get('mode')||'interview';if(!['interview','chart','email'].includes(mode))mode='interview';const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));const save=()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}};const level=()=>Number(el('level').value);const id=()=>level()+':'+mode;
function chart(d){const max=Math.max(...d.values)*1.2;const left=60,base=235,width=540,height=190;const step=width/d.values.length;const bars=d.values.map((v,i)=>{const h=v/max*height,x=left+i*step+step*.18,y=base-h,w=step*.64;return '<rect class="'+(i===d.values.length-1?'bar-alt':'bar')+'" x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" rx="5"/><text x="'+(x+w/2)+'" y="'+(y-8)+'" text-anchor="middle">'+v+'</text><text x="'+(x+w/2)+'" y="258" text-anchor="middle">'+esc(d.labels[i])+'</text>'}).join('');return '<svg class="studio-chart" role="img" aria-label="'+esc(d.title)+': '+d.labels.map((x,i)=>x+' '+d.values[i]).join(', ')+'" viewBox="0 0 660 290"><text x="24" y="26">'+esc(d.unit)+'</text><line class="axis" x1="60" y1="235" x2="610" y2="235"/>'+bars+'</svg>'}
function progress(){el('progress').textContent=Object.values(state.answers||{}).filter(Boolean).length+' respostas salvas nas 15 atividades disponíveis.'}
function render(){state.level=level();save();document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));const i=level(),d=mode==='interview'?interviews[i]:mode==='email'?emails[i]:chartData[i];let head='';if(mode==='interview')head='<p class="ey">INTERVIEW QUESTION</p><h2>'+esc(d.q)+'</h2><p>'+esc(d.task)+'</p><details><summary>Ver exemplo de resposta</summary><p class="studio-example">'+esc(d.a)+'</p></details>';if(mode==='email')head='<p class="ey">EMAIL SIMULATION</p><h2>'+esc(d.subject)+'</h2><p>'+esc(d.task)+'</p><details><summary>Ver e-mail modelo</summary><p class="studio-example"><b>Subject: '+esc(d.subject)+'</b>\n'+esc(d.from)+'</p></details><p><b>Checklist:</b> '+esc(d.criteria)+'</p>';if(mode==='chart')head='<p class="ey">DATA PRESENTATION · DADOS FICTÍCIOS</p><h2>'+esc(d.title)+'</h2>'+chart(d)+'<p>'+esc(d.task)+'</p><details><summary>Ver exemplo de apresentação</summary><p class="studio-example">'+esc(d.model)+'</p></details>';const answer=(state.answers||{})[id()]||'';el('activity').innerHTML=head+'<label for="answer">Sua '+(mode==='email'?'mensagem':mode==='chart'?'apresentação':'resposta')+' em inglês</label><textarea id="answer" maxlength="3000" placeholder="Write in English...">'+esc(answer)+'</textarea><details class="flow-review"><summary>Revisar minha escrita e fala</summary><ul><li>Minha mensagem principal é compreensível?</li><li>Atendi ao objetivo e indiquei o próximo passo?</li><li>Usei uma expressão da atividade com sentido adequado?</li><li>Organizei as ideias e adaptei o tom ao interlocutor?</li></ul><p>Compare com o modelo, escolha uma melhoria, edite sua resposta e pratique novamente sem ler. Outras respostas são possíveis.</p><p>Salvar registra prática. Acerto objetivo, autoavaliação e avaliação por professor são diferentes; esta atividade não recebeu correção automática ou avaliação por professor.</p></details><div class="actions"><button id="saveAnswer" class="primary">Salvar atividade</button><button id="clearAnswer" class="ghost">Limpar resposta</button></div><p id="status" class="studio-status" role="status"></p>';el('saveAnswer').onclick=()=>{state.answers??={};state.answers[id()]=el('answer').value.trim();save();progress();el('status').textContent='Resposta salva. Compare com o modelo e revise sua linguagem.'};el('clearAnswer').onclick=()=>{el('answer').value='';el('status').textContent='Campo limpo; clique em salvar para atualizar o registro.'};progress()}
el('level').value=String(Math.max(0,Math.min(4,Number(state.level)||0)));el('level').onchange=render;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render()});render();
