/* Resilient local progress storage with last-known-good snapshots and portable backup. */
window.ISMStorage=(()=>{
 'use strict';
 const blocked=new Set(),prefix='ismbe:',snapshotPrefix='ismbe:backup:lastgood:';
 const object=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
 let statusTimer=null;
 function warn(message){let el=document.getElementById('save-warning');if(!el){el=document.createElement('p');el.id='save-warning';el.setAttribute('role','alert');el.style.cssText='padding:16px;margin:16px;border:2px solid #e9a83a;background:#00162c;color:white;font:16px/1.5 system-ui';document.body.prepend(el);}el.textContent=message;}
 function status(message,bad=false){let el=document.getElementById('save-status');if(!el){el=document.createElement('div');el.id='save-status';el.setAttribute('role','status');el.setAttribute('aria-live','polite');el.style.cssText='position:fixed;right:12px;bottom:calc(82px + env(safe-area-inset-bottom));z-index:30;padding:7px 10px;border-radius:10px;background:#062b3b;color:#fff;font:700 12px/1.3 system-ui;box-shadow:0 5px 16px #00162c33;opacity:0;transition:opacity .18s';document.body.append(el);}el.textContent=message;el.style.background=bad?'#7b3030':'#062b3b';el.style.opacity='1';clearTimeout(statusTimer);statusTimer=setTimeout(()=>el.style.opacity='0',1800);}
 function valid(raw){const value=JSON.parse(raw);if(!value||typeof value!=='object'||Array.isArray(value))throw Error('invalid');return value;}
 function read(key,fallback){try{const raw=localStorage.getItem(key)??(fallback?localStorage.getItem(fallback):null);if(raw===null)return {};return valid(raw);}catch{blocked.add(key);warn('Não foi possível recuperar o progresso. O registro original foi preservado. Use Dados e backup para exportar seus registros antes de tentar uma recuperação.');return {};}}
 function write(key,value){if(blocked.has(key)){warn('O salvamento está suspenso para preservar um registro que não pôde ser lido. Exporte seus dados antes de continuar.');status('Salvamento suspenso',true);return false;}try{const next=JSON.stringify(value);valid(next);const previous=localStorage.getItem(key);if(previous!==null){try{valid(previous);localStorage.setItem(snapshotPrefix+key,previous);}catch{}}localStorage.setItem(key,next);status('Progresso salvo');return true;}catch{warn('O navegador não conseguiu salvar suas alterações. Mantenha esta página aberta e exporte seus dados antes de sair.');status('Falha ao salvar',true);return false;}}
 function collect(){const data={format:'ism-business-backup-v1',createdAt:new Date().toISOString(),origin:location.origin,records:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith(prefix)&&!k.startsWith(snapshotPrefix)){const raw=localStorage.getItem(k);try{JSON.parse(raw);data.records[k]=JSON.parse(raw);}catch{data.records[k]={__unreadable:true,raw};}}}return data;}
 function exportBackup(){const data=collect(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ism-business-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status('Backup exportado');return data;}
 async function importBackup(file){const text=await file.text(),data=JSON.parse(text);if(data?.format!=='ism-business-backup-v1'||!data.records||typeof data.records!=='object'||Array.isArray(data.records))throw Error('backup inválido');const entries=Object.entries(data.records).filter(([k,v])=>k.startsWith(prefix)&&!k.startsWith(snapshotPrefix)&&v&&typeof v==='object'&&!Array.isArray(v)&&!v.__unreadable);if(!entries.length)throw Error('backup sem registros válidos');entries.forEach(([k,v])=>{const old=localStorage.getItem(k);if(old!==null)localStorage.setItem(snapshotPrefix+k,old);localStorage.setItem(k,JSON.stringify(v));blocked.delete(k);});status('Backup restaurado');return entries.length;}
 function restoreLastGood(key){const raw=localStorage.getItem(snapshotPrefix+key);if(!raw)return false;try{valid(raw);localStorage.setItem(key,raw);blocked.delete(key);status('Última versão válida restaurada');return true;}catch{return false;}}
 function mountBackupUI(){if(document.getElementById('ism-data-backup'))return;const main=document.querySelector('main');if(!main)return;const d=document.createElement('details');d.id='ism-data-backup';d.className='data-backup';d.style.cssText='margin:0 0 14px;padding:10px 12px;border:1px solid var(--surface-border,#dde7ea);border-radius:12px;background:var(--surface,#fff);color:var(--surface-text,#102a35)';d.innerHTML='<summary style="cursor:pointer;font-weight:800">Dados e backup</summary><p style="font-size:13px;margin:9px 0">Seu progresso é salvo neste aparelho. Exporte uma cópia antes de trocar de navegador ou dispositivo.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button type="button" class="mini" data-export>EXPORTAR BACKUP</button><label class="mini" style="display:inline-flex;align-items:center;cursor:pointer">RESTAURAR BACKUP<input data-import type="file" accept="application/json" hidden></label></div><p data-note role="status" style="font-size:12px;margin:8px 0 0"></p>';d.querySelector('[data-export]').onclick=exportBackup;d.querySelector('[data-import]').onchange=async e=>{const note=d.querySelector('[data-note]');try{const n=await importBackup(e.target.files[0]);note.textContent=n+' registros restaurados. Recarregando…';setTimeout(()=>location.reload(),700);}catch{note.textContent='Não foi possível restaurar: selecione um backup válido do ISM Business English.';}e.target.value='';};main.prepend(d);}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mountBackupUI);else mountBackupUI();
 return {read,write,object,collect,exportBackup,importBackup,restoreLastGood};
})();