const path=require('path');process.chdir(path.join(__dirname,'..'));const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c={window:{}};vm.createContext(c);
for(const n of ['premium-courses.js','premium-engine.js'])vm.runInContext(fs.readFileSync(''+n,'utf8'),c);
const courses=c.window.ISM_PREMIUM_COURSES,E=c.window.ISMPremiumEngine;assert.deepEqual(Array.from(courses,x=>x.lessons.length),[7,8,9,8,9,9]);let lessons=0,phrases=0,words=0;const titles=new Set();
for(const course of courses){const state={};course.lessons.forEach((l,i)=>{lessons++;assert.equal(l.length,13,course.id+':'+i);for(const j of [0,1,2,5,8,10,11])assert.equal(typeof l[j],'string');assert(!titles.has(l[0]),l[0]);titles.add(l[0]);assert.equal(l[3].length,4);assert(l[3].every(x=>typeof x==='string'&&x.length>10));phrases+=2;assert.equal(l[4].length,2);assert(l[4].every(x=>x.split('|').length===2));words+=2;assert.equal(l[6].length,3);assert.equal(new Set(l[6]).size,3);assert(l[7]>=0&&l[7]<3);assert(l[9].length>=3);assert(l[9][0].includes('___'));assert.equal(l[12].length,2);assert(l[11].split(/\s+/).length>=15);assert.equal(new Set(E.order(l,i)).size,3);assert(E.order(l,i).includes(l[7]));assert(E.gapOK(l[9][1].toUpperCase()+'!',l));assert(!E.gapOK('incorrect',l));const record=E.record(null);assert(!E.ready(record,l));Object.assign(record,{choiceCorrect:true,gapCorrect:true,draft:'A personal response.',model:true,criteria:[true,true],oral:true});assert(E.ready(record,l));record.criteria[1]=false;assert(!E.ready(record,l));state[E.lessonId(course,i)]={done:true};assert.equal(E.route('#'+course.id+'/'+(i+1),courses).index,i);});assert.equal(E.count(course,state),course.lessons.length);state['unexpected']={done:true};assert.equal(E.count(course,state),course.lessons.length);assert(!E.key(course.id).includes('ismbe:v9'));assert.equal(E.route('#'+course.id+'/999',courses).index,null);}
assert.equal(lessons,50);assert.equal(new Set(courses.map(x=>E.key(x.id))).size,6);assert.equal(E.route('#bad',courses).course,null);assert.equal(E.record({criteria:'x',draft:1,gap:null}).draft,'');
for(const n of ['premium-study.js','premium-engine.js','premium-courses.js'])new vm.Script(fs.readFileSync(''+n,'utf8'));
const index=fs.readFileSync('index.html','utf8');for(const m of index.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);assert(index.includes("premium.html#"));assert(!index.includes('• EM PLANEJAMENTO'));
const html=fs.readFileSync('premium.html','utf8');for(const m of html.matchAll(/(?:src|href)="([^"#?]+)(?:\?[^"#]*)?"/g)){if(!m[1].includes(':'))assert(fs.existsSync(''+m[1]),m[1]);}
console.log(JSON.stringify({lessons,phrases,words,objectiveExercises:lessons*2,writingTasks:lessons,oralTasks:lessons,checks:'PASS: schema, unique titles, answers, gap validation, completion criteria, independent keys, progress counts, all lesson routes, syntax and local assets'}));
