import { gatewayOnly } from '../../_shared/gateway-only.mjs';
const H={'Cache-Control':'no-store, private','Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS'};
const stages=[
{id:1,key:'diagnose',title:'Interview Readiness Check',pt:'Diagnóstico de preparação',type:'diagnostic',minutes:8,required:true,outcomes:['Identify target role and interview context','Self-rate confidence in storytelling, STAR, difficult questions and closing','Choose three priority skills'],next:'profile'},
{id:2,key:'profile',title:'Build Your Interview Profile',pt:'Construa seu perfil de entrevista',type:'builder',minutes:20,required:true,outcomes:['Define target role and current value','Collect truthful evidence and achievements','Prepare strengths, development area and motivation'],next:'foundations'},
{id:3,key:'foundations',title:'Interview Foundations',pt:'Fundamentos de entrevista',type:'course',source:{modules:[13,14]},lessonCount:12,required:true,outcomes:['First impressions','Current role and career path','Tell Me About Yourself','Professional value and career transitions'],gate:{requires:['profile']},next:'star-bank'},
{id:4,key:'star-bank',title:'Build Your STAR Story Bank',pt:'Construa seu banco de histórias STAR',type:'builder',minutes:35,required:true,targetStories:5,categories:['achievement','problem solving','conflict','deadline','initiative'],outcomes:['Create at least five truthful reusable stories','Strengthen Action and Result','Attach each story to likely interview questions'],gate:{requires:['foundations']},next:'behavioral'},
{id:5,key:'behavioral',title:'Behavioral Interview Skills',pt:'Entrevistas comportamentais',type:'course',source:{modules:[15]},lessonCount:6,required:true,outcomes:['Recognize behavioral questions','Use STAR efficiently','Show personal contribution and measurable impact'],gate:{requires:['star-bank']},next:'pressure'},
{id:6,key:'pressure',title:'Difficult Questions Under Pressure',pt:'Perguntas difíceis sob pressão',type:'course',source:{modules:[16]},lessonCount:6,required:true,outcomes:['Strengths with evidence','Real development areas','Failure and conflict','Thinking time and structured answers'],gate:{requires:['behavioral']},next:'fit-close'},
{id:7,key:'fit-close',title:'Fit, Salary & Closing',pt:'Fit, salário e encerramento',type:'course',source:{modules:[17]},lessonCount:6,required:true,outcomes:['Why this company/role','Positive reasons for leaving','Salary expectations','Candidate questions and closing'],gate:{requires:['pressure']},next:'guided-mocks'},
{id:8,key:'guided-mocks',title:'Guided Interview Simulations',pt:'Simulações guiadas',type:'simulation',source:{ids:['P1.mock1','P1.mock2','P1.mock3','P1.mock4']},simulationCount:4,required:true,outcomes:['Practice professional story','Practice STAR','Handle difficult questions','Discuss salary and close'],gate:{requires:['fit-close']},next:'full-mock'},
{id:9,key:'full-mock',title:'Full Mock Interview',pt:'Entrevista simulada completa',type:'assessment',minutes:18,required:true,outcomes:['Complete a realistic interview sequence','Respond without reading scripts','Use evidence from profile and STAR bank','Reflect on strengths and next priorities'],gate:{requires:['guided-mocks'],recommended:{starStories:5}},next:'action-plan'},
{id:10,key:'action-plan',title:'Personal Interview Action Plan',pt:'Plano pessoal de entrevista',type:'reflection',minutes:10,required:true,outcomes:['Choose three answers to improve','Choose two language targets','Schedule another mock attempt','Record one concrete next action'],gate:{requires:['full-mock']},next:null}
];
const diagnostic={scale:{min:1,max:5,labels:{1:'I need significant support',3:'I can do this with preparation',5:'I can do this confidently and naturally'}},items:[{id:'intro',skill:'Professional introduction',prompt:'I can introduce myself clearly in 45–90 seconds.'},{id:'value',skill:'Professional value',prompt:'I can explain what I bring to the target role with evidence.'},{id:'star',skill:'STAR stories',prompt:'I can answer behavioral questions using specific examples.'},{id:'difficult',skill:'Difficult questions',prompt:'I can discuss weaknesses, mistakes and conflict without becoming defensive.'},{id:'motivation',skill:'Motivation & fit',prompt:'I can explain why I want the role/company specifically.'},{id:'salary',skill:'Salary',prompt:'I can discuss salary expectations professionally.'},{id:'questions',skill:'Candidate questions',prompt:'I can ask thoughtful questions about success, challenges and the team.'},{id:'spoken',skill:'Spoken delivery',prompt:'I can answer without reading or memorizing a script.'}],rule:'Use the diagnostic to prioritize practice, not to label English proficiency.'};
const mastery={requirements:[{id:'profile',label:'Interview Profile completed'},{id:'stories',label:'At least 5 STAR stories prepared'},{id:'lessons',label:'30/30 Job Interview lessons completed'},{id:'guided',label:'4 guided simulations completed'},{id:'mock',label:'Full Mock Interview completed'},{id:'reflection',label:'Action Plan completed'}],achievement:'GLOBAL INTERVIEWER',principle:'Mastery means demonstrated preparation and repeated practice, not memorization or a hiring guarantee.'};
const pedagogy={sequence:['DIAGNOSE','BUILD','LEARN','PRACTICE','SIMULATE','REFLECT','REPEAT'],rules:['Personalize answers with truthful evidence.','Teach frameworks, not scripts to memorize.','Prefer concise relevance over exhaustive biography.','Behavioral answers prioritize Action and Result.','Speaking practice should progressively remove written support.','Automated feedback is formative unless a validated scoring system is introduced.'],supportLevels:[{level:1,label:'Model',support:'Full model + bilingual guidance'},{level:2,label:'Guided',support:'Framework + prompts + useful language'},{level:3,label:'Independent',support:'Question only + optional thinking time'},{level:4,label:'Mock',support:'No answer scaffold during response'}]};
Deno.serve(async(req)=>{const denied=await gatewayOnly(req,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'));if(denied)return denied;if(req.method==='OPTIONS')return new Response('ok',{headers:H});const u=new URL(req.url),section=u.searchParams.get('section'),stage=Number(u.searchParams.get('stage'));const all={stages,diagnostic,mastery,pedagogy};let data=stage?stages.find(s=>s.id===stage)||null:section?(all as any)[section]??null:all;return new Response(JSON.stringify({ok:data!==null,version:1,tier:'PREMIUM',track:'JOB_INTERVIEWS',title:'Job Interview Mastery Path',pt:'Jornada de Domínio em Entrevistas',stageCount:stages.length,lessonCount:30,guidedSimulationCount:4,data}),{headers:H,status:data===null?404:200})});
