const H={'Content-Type':'application/json','Access-Control-Allow-Origin':'*'};
const lesson=(id,title,pt,objective,context,learn,practice,speak,minutes=8)=>({id,title,pt,objective,context,learn,notice:'Use the language to achieve a professional outcome. Adapt the model to your own context instead of memorizing it.',practice,speak,check:'Can you use the target language naturally in a realistic professional situation?',minutes});
const P=(prompt,options,answer,feedback)=>({prompt,options,answer,feedback});
const modules=[
{id:'P2',order:2,title:'Professional Emails & Messages',pt:'E-mails e Mensagens Profissionais',goal:'Write clear, concise and professional messages across email, chat and follow-up situations.',achievement:'PROFESSIONAL WRITER',lessons:[
lesson('P2.1','Subject Lines & Clear Purpose','Assunto e objetivo claro','Make the purpose of a message immediately clear.','You need a busy colleague to understand your request quickly.',[['I’m writing to confirm…','Estou escrevendo para confirmar…'],['Could you please send… by…?','Você poderia enviar… até…?']],P('Which opening is clearest?',['I am contacting you regarding the revised timeline.','Hello, I have something to ask.'],0,'State the topic and purpose early.'),'Write a short email opening for a real request.'),
lesson('P2.2','Professional Tone','Tom profissional','Choose formal, neutral or concise language appropriately.','A correct sentence can still sound abrupt in an international workplace.',[['Could you please take a look at this?','Você poderia dar uma olhada nisso?'],['When you have a moment, could you…?','Quando tiver um momento, poderia…?']],P('Choose the more diplomatic request.',['Send me the file today.','Could you send me the file by the end of the day, please?'],1,'Professional tone combines clarity and courtesy.'),'Turn a direct command into a professional request.'),
lesson('P2.3','Requests & Deadlines','Pedidos e prazos','Make actionable requests with clear deadlines.','Your message needs an owner, action and deadline.',[['Could you confirm this by Friday?','Poderia confirmar isso até sexta?'],['Would it be possible to…?','Seria possível…?']],P('What makes a request actionable?',['A clear action and deadline.','A long explanation.'],0,'Action + deadline reduces ambiguity.'),'Ask a colleague for an update by a specific time.'),
lesson('P2.4','Follow-ups & Reminders','Follow-ups e lembretes','Follow up without sounding aggressive.','A client has not replied to your previous message.',[['I’m following up on my message below.','Estou retomando minha mensagem abaixo.'],['Just a quick reminder that…','Apenas um lembrete rápido de que…']],P('Best neutral follow-up?',['Why haven’t you replied?','I’m following up on the proposal I sent on Monday.'],1,'Refer to the previous message and next action.'),'Write a polite follow-up referring to your previous message and requesting a clear next action.'),
lesson('P2.5','Bad News & Apologies','Más notícias e desculpas','Communicate delays or problems responsibly.','A deadline will not be met.',[['I’m afraid we’ll need an additional two days.','Receio que precisaremos de mais dois dias.'],['I apologize for the delay.','Peço desculpas pelo atraso.']],P('Strong professional structure?',['Problem only.','Acknowledge + explain + solution + next step.'],1,'Ownership and solution protect trust.'),'Explain a delay and propose a solution.'),
lesson('P2.6','Chat, Teams & Slack','Chat, Teams e Slack','Write concise workplace chat messages.','Chat is faster than email but still needs context and tone.',[['Quick question about the timeline…','Pergunta rápida sobre o cronograma…'],['Are you available for a quick call?','Você está disponível para uma ligação rápida?']],P('Best chat message?',['Call me.','Are you available for a quick call about the client update?'],1,'Short does not mean context-free.'),'Write a concise Teams/Slack request.'),
lesson('P2.7','Email Editing Challenge','Desafio de edição','Edit unclear messages for clarity, tone and action.','You receive a vague, overly direct draft.',[['To confirm, the next step is…','Para confirmar, o próximo passo é…'],['Please let me know if you have any questions.','Por favor, avise se tiver alguma dúvida.']],P('What should you check before sending?',['Purpose, tone, action and deadline.','Only grammar.'],0,'Professional writing is more than grammatical accuracy.'),'Rewrite a real or imagined workplace email.'),
lesson('P2.8','Professional Writing Challenge','Desafio final','Produce a complete professional message independently.','A stakeholder needs an update, a request and a deadline.',[['Here’s a quick update on…','Segue uma atualização rápida sobre…'],['The next step is…','O próximo passo é…']],P('What should the reader know at the end?',['What happened and what to do next.','Every project detail.'],0,'Optimize for reader action.'),'Create a complete email: context, update, request, deadline and close.',10)]},
{id:'P3',order:3,title:'Networking & Professional Relationships',pt:'Networking e Relacionamentos Profissionais',goal:'Start, sustain and close professional conversations naturally and build relationships after the first contact.',achievement:'GLOBAL NETWORKER',lessons:[
lesson('P3.1','Starting a Conversation','Iniciando uma conversa','Open a professional conversation naturally.','You are attending an international conference.',[["What brings you to the event?",'O que trouxe você ao evento?'],["How are you finding the conference so far?",'O que está achando da conferência até agora?']],P('Best networking opener?',['What is your salary?','What brings you to the event?'],1,'Use open, low-risk professional questions.'),'Open a conversation at an event.'),
lesson('P3.2','Your Professional Introduction','Sua apresentação profissional','Introduce yourself without reciting your CV.','Someone asks what you do.',[["I work in… and I mainly focus on…",'Trabalho em… e foco principalmente em…'],["At the moment, I’m working on…",'No momento, estou trabalhando em…']],P('A useful introduction should emphasize…',['Role, focus and relevance.','Your complete work history.'],0,'Keep it conversational.'),'Give a 20-second introduction.'),
lesson('P3.3','Keeping the Conversation Going','Mantendo a conversa','Use follow-up questions and active listening.','The other person mentions a new project.',[["That sounds interesting. How did that come about?",'Parece interessante. Como isso surgiu?'],["What has been the biggest challenge?",'Qual tem sido o maior desafio?']],P('Best way to sustain conversation?',['Ask a relevant follow-up.','Immediately change topic.'],0,'Build from what the person just said.'),'Ask two connected follow-up questions.'),
lesson('P3.4','Talking About Your Company & Work','Falando sobre empresa e trabalho','Explain your work clearly to an international contact.','Your listener does not know your company.',[["We specialize in…",'Somos especializados em…'],["Our main clients are…",'Nossos principais clientes são…']],P('What should you avoid?',['Clear examples.','Internal jargon the listener may not know.'],1,'Translate internal language into audience-friendly English.'),'Explain your company in three sentences.'),
lesson('P3.5','Closing & Exchanging Contacts','Encerrando e trocando contatos','End naturally and create a next step.','You need to move to another conversation.',[["It was great talking to you.",'Foi ótimo conversar com você.'],["Would you like to connect on LinkedIn?",'Gostaria de se conectar no LinkedIn?']],P('Strong close?',['Disappear without closing.','Close warmly and suggest a next step.'],1,'A clear next step makes networking useful.'),'Close a networking conversation.'),
lesson('P3.6','LinkedIn & Follow-up','LinkedIn e follow-up','Send a personalized post-event follow-up.','You connected with someone yesterday.',[["It was great meeting you yesterday.",'Foi ótimo conhecer você ontem.'],["I enjoyed our conversation about…",'Gostei da nossa conversa sobre…']],P('Best follow-up includes…',['A specific reference to the conversation.','A generic sales pitch.'],0,'Specificity makes the message human.'),'Write a LinkedIn follow-up.'),
lesson('P3.7','Networking Challenge','Desafio de networking','Manage a complete professional networking interaction.','You meet a potential international partner.',[["I’d be interested to hear more about…",'Gostaria de saber mais sobre…'],["Let’s stay in touch.",'Vamos manter contato.']],P('Complete networking flow?',['Open → connect → explore → close → follow up.','Pitch continuously.'],0,'Relationship comes before transaction.'),'Simulate a 60-second networking conversation.',10)]},
{id:'P4',order:4,title:'Working in Global Teams',pt:'Trabalhando em Equipes Globais',goal:'Collaborate across cultures, time zones and communication styles with clarity and accountability.',achievement:'GLOBAL TEAM PLAYER',lessons:[
lesson('P4.1','Global Communication Styles','Estilos de comunicação global','Recognize differences in directness and context.','A message sounds unusually direct to you.',[["Just to make sure we’re aligned…",'Só para garantir que estamos alinhados…'],["How would you prefer us to handle this?",'Como você prefere que lidemos com isso?']],P('Best response to style differences?',['Assume bad intent.','Clarify expectations.'],1,'Do not confuse style with intention.'),'Clarify a communication preference.'),
lesson('P4.2','Ownership & Responsibilities','Responsabilidades e ownership','Clarify who owns what.','A global project has overlapping responsibilities.',[["I’ll take ownership of…",'Vou assumir a responsabilidade por…'],["Who will be responsible for…?",'Quem será responsável por…?']],P('Useful alignment question?',['Who owns the next step?','Who is to blame?'],0,'Make ownership explicit.'),'State your responsibility and confirm another owner.'),
lesson('P4.3','Status Updates','Atualizações de status','Give concise project updates.','Your distributed team needs an asynchronous update.',[["We’re on track to…",'Estamos no caminho para…'],["The main blocker is…",'O principal impedimento é…']],P('Strong update structure?',['Progress + blocker + next step.','Background only.'],0,'Make status actionable.'),'Give a 30-second project update.'),
lesson('P4.4','Deadlines & Expectations','Prazos e expectativas','Align realistic expectations before problems grow.','Two offices interpret “soon” differently.',[["Can we agree on a specific deadline?",'Podemos combinar um prazo específico?'],["Friday at 17:00 UTC works for me. Please confirm the date in the invitation.",'Sexta-feira às 17h UTC funciona para mim. Confirme a data no convite.']],P('Best practice?',['Use vague time expressions.','Confirm exact dates/times.'],1,'Specificity is especially important across time zones.'),'Negotiate a realistic deadline.'),
lesson('P4.5','Asking for Help','Pedindo ajuda','Ask for support without losing ownership.','You are blocked by a dependency.',[["I’m currently blocked by…",'No momento estou bloqueado por…'],["Could you help me with…?",'Você poderia me ajudar com…?']],P('Good help request includes…',['Blocker, needed help and timing.','Only “help”.'],0,'Make it easy for the other person to act.'),'Ask for help on a project.'),
lesson('P4.6','Time Zones & Async Work','Fusos e trabalho assíncrono','Collaborate without requiring everyone online.','Your team spans three continents.',[["No need to reply outside your working hours.",'Não precisa responder fora do seu horário de trabalho.'],["I’ll leave the update here for when you’re online.",'Vou deixar a atualização aqui para quando você estiver online.']],P('Healthy global-team behavior?',['Expect instant replies 24/7.','Design for asynchronous work.'],1,'Respect time zones and document decisions.'),'Send an async handoff.'),
lesson('P4.7','Misunderstandings & Repair','Mal-entendidos e reparo','Repair misunderstandings constructively.','Two teams interpreted a decision differently.',[["I think we may have understood this differently.",'Acho que podemos ter entendido isso de forma diferente.'],["Let me clarify what I meant.",'Deixe-me esclarecer o que quis dizer.']],P('Best first move?',['Assign blame.','Clarify the difference neutrally.'],1,'Repair the shared understanding first.'),'Correct a misunderstanding diplomatically.'),
lesson('P4.8','Global Team Challenge','Desafio de equipe global','Coordinate a realistic cross-border project interaction.','A deadline is at risk and two offices need alignment.',[["Here’s where we are right now…",'Aqui está nossa situação atual…'],["Can we agree on the following next steps?",'Podemos concordar com os seguintes próximos passos?']],P('What creates alignment?',['Clear status, ownership and next steps.','More meetings only.'],0,'Alignment is an outcome, not a meeting count.'),'Deliver a global-team alignment update.',10)]},
{id:'P5',order:5,title:'Negotiation & Persuasion',pt:'Negociação e Persuasão',goal:'Negotiate scope, deadlines, proposals and trade-offs while protecting relationships.',achievement:'BUSINESS NEGOTIATOR',lessons:[
lesson('P5.1','Understanding Interests','Entendendo interesses','Explore what the other side really needs.','A client demands an aggressive deadline.',[["What is driving that deadline?",'O que está motivando esse prazo?'],["What would be most important for you?",'O que seria mais importante para você?']],P('Before making concessions, first…',['Explore interests.','Say yes immediately.'],0,'Positions are not always the underlying need.'),'Ask two diagnostic questions.'),
lesson('P5.2','Making a Proposal','Fazendo uma proposta','Present a clear proposal with rationale.','You want a different implementation plan.',[["What we propose is…",'O que propomos é…'],["The advantage of this approach is…",'A vantagem desta abordagem é…']],P('Persuasive proposal?',['Recommendation + reason + benefit.','Recommendation only.'],0,'Connect the proposal to value.'),'Make a proposal in three sentences.'),
lesson('P5.3','Conditions & Trade-offs','Condições e trocas','Negotiate conditional concessions.','The client asks for faster delivery.',[["We could do that provided that…",'Poderíamos fazer isso desde que…'],["If we move the deadline, we’d need to…",'Se mudarmos o prazo, precisaríamos…']],P('Useful negotiation principle?',['Give concessions for free.','Link concessions to conditions.'],1,'Trade rather than simply concede.'),'Offer a conditional concession.'),
lesson('P5.4','Pushing Back Professionally','Resistindo profissionalmente','Set limits without damaging rapport.','A request creates unacceptable risk.',[["I’m not sure we can commit to that timeline.",'Não tenho certeza se podemos nos comprometer com esse prazo.'],["My concern is the impact on quality.",'Minha preocupação é o impacto na qualidade.']],P('Strong pushback?',['No. Impossible.','Concern + reason + alternative.'],1,'Protect the relationship while protecting the constraint.'),'Push back on an unrealistic request.'),
lesson('P5.5','Counterproposals','Contrapropostas','Respond to an offer with a workable alternative.','The first proposal does not meet your needs.',[["Could we look at a different option?",'Poderíamos considerar uma opção diferente?'],["What if we…?",'E se nós…?']],P('A counterproposal should…',['Move the discussion forward.','Only reject.'],0,'Give the conversation somewhere to go.'),'Make a counterproposal.'),
lesson('P5.6','Handling Objections','Lidando com objeções','Acknowledge and respond to concerns persuasively.','A stakeholder questions the cost.',[["I understand the concern about cost.",'Entendo a preocupação com o custo.'],["The reason we recommend this is…",'O motivo pelo qual recomendamos isso é…']],P('First response to an objection?',['Acknowledge it.','Dismiss it.'],0,'Recognition lowers resistance.'),'Respond to a cost objection.'),
lesson('P5.7','Reaching Agreement','Chegando a um acordo','Confirm terms and avoid ambiguity.','Both sides appear to agree.',[["So, just to confirm, we’ve agreed that…",'Então, só para confirmar, concordamos que…'],["I’ll send the revised terms today.",'Enviarei os termos revisados hoje.']],P('Before ending negotiation…',['Confirm terms and next steps.','Assume everyone remembers.'],0,'Agreement needs explicit confirmation.'),'Summarize an agreement.'),
lesson('P5.8','Deadline Negotiation Simulation','Simulação de prazo','Negotiate a deadline under pressure.','A strategic client wants delivery one week earlier.',[["We can bring it forward if…",'Podemos antecipar se…'],["The earliest realistic date would be…",'A data realista mais próxima seria…']],P('Your goal is to…',['Protect value and find a workable trade-off.','Win every point.'],0,'Good negotiation creates a workable agreement.'),'Negotiate the deadline aloud.',10),
lesson('P5.9','Negotiation Challenge','Desafio de negociação','Run a complete negotiation from discovery to agreement.','Scope, price and timeline all need alignment.',[["Let me make sure I understand your priority.",'Deixe-me confirmar se entendi sua prioridade.'],["Would that work for you?",'Isso funcionaria para você?']],P('Complete flow?',['Explore → propose → trade → resolve → confirm.','Argue → win.'],0,'Structure supports influence.'),'Deliver a complete negotiation response.',12)]},
{id:'P6',order:6,title:'Feedback, Conflict & Difficult Conversations',pt:'Feedback, Conflitos e Conversas Difíceis',goal:'Handle sensitive workplace conversations with clarity, respect and solutions.',achievement:'DIFFICULT CONVERSATION PRO',lessons:[
lesson('P6.1','Giving Constructive Feedback','Dando feedback construtivo','Give specific, useful feedback.','A colleague’s behavior affected a client meeting.',[["I’d like to give you some feedback on…",'Gostaria de dar um feedback sobre…'],["What I noticed was…",'O que percebi foi…']],P('Useful feedback focuses on…',['Observable behavior and impact.','Personality labels.'],0,'Be specific and actionable.'),'Give feedback using behavior + impact.'),
lesson('P6.2','Receiving Feedback','Recebendo feedback','Respond without becoming defensive.','Your manager raises a concern.',[["Thanks for pointing that out.",'Obrigado por apontar isso.'],["Could you give me an example?",'Poderia me dar um exemplo?']],P('Strong response?',['Defend immediately.','Listen, clarify and respond.'],1,'Understanding comes before explanation.'),'Respond to critical feedback.'),
lesson('P6.3','Admitting Mistakes','Admitindo erros','Take responsibility and recover trust.','You made an error that affected delivery.',[["I take responsibility for that.",'Assumo a responsabilidade por isso.'],["Here’s what I’m doing to fix it.",'Aqui está o que estou fazendo para corrigir.']],P('Trust-building structure?',['Own + fix + prevent.','Excuse + blame.'],0,'Accountability should include action.'),'Admit a mistake professionally.'),
lesson('P6.4','Disagreeing with Your Manager','Discordando do gestor','Challenge upward diplomatically.','You see a significant risk in your manager’s plan.',[["I understand the rationale. My concern is…",'Entendo a lógica. Minha preocupação é…'],["Could we consider…?",'Poderíamos considerar…?']],P('Best approach?',['Attack the decision.','Acknowledge + concern + evidence + alternative.'],1,'Challenge the idea, not the authority.'),'Disagree upward.'),
lesson('P6.5','Addressing Conflict','Abordando conflitos','Name a problem without escalating it.','Two colleagues are repeatedly misaligned.',[["I’d like us to address what’s happening.",'Gostaria que abordássemos o que está acontecendo.'],["How can we prevent this from happening again?",'Como podemos evitar que isso aconteça novamente?']],P('Conflict language should be…',['Neutral and future-focused.','Accusatory.'],0,'Move from blame to resolution.'),'Open a conflict-resolution conversation.'),
lesson('P6.6','Setting Boundaries','Estabelecendo limites','Say no or renegotiate capacity professionally.','You receive another urgent request with no capacity.',[["I can take this on, but I’d need to move…",'Posso assumir isso, mas precisaria mover…'],["I don’t have the capacity to complete both by Friday.",'Não tenho capacidade para concluir ambos até sexta.']],P('Professional boundary?',['Explain constraint and trade-off.','Say yes and fail later.'],0,'Make capacity visible.'),'Renegotiate competing priorities.'),
lesson('P6.7','Delivering Bad News','Comunicando más notícias','Communicate a difficult decision clearly and respectfully.','A project must be delayed.',[["I need to let you know that…",'Preciso informar que…'],["I realize this has an impact on…",'Percebo que isso tem impacto em…']],P('Bad-news structure?',['Clear message + impact + reason + next step.','Hide the message.'],0,'Do not bury the decision.'),'Communicate a delay.'),
lesson('P6.8','Difficult Conversation Challenge','Desafio de conversa difícil','Use a complete repair-and-solution structure.','A repeated behavior is affecting team performance.',[['I’d like to understand your perspective.','Gostaria de entender sua perspectiva.'],['Can we agree on what happens next?','Podemos concordar sobre o que acontece a seguir?']],P('Complete structure?',['Acknowledge → explain → position → solution → confirm.','Blame → demand.'],0,'A structured conversation protects clarity and respect.'),'Handle the conversation aloud.',12)]},
{id:'P7',order:7,title:'Leadership & People Management',pt:'Liderança e Gestão de Pessoas',goal:'Lead, delegate, coach and manage performance confidently in English.',achievement:'GLOBAL LEADER',lessons:[
lesson('P7.1','Setting Expectations','Definindo expectativas','Set clear outcomes and standards.','A new team member starts a project.',[["What success looks like is…",'O que caracteriza sucesso é…'],["The key priorities are…",'As prioridades principais são…']],P('Clear expectation includes…',['Outcome, standard and timing.','General encouragement only.'],0,'Clarity is a leadership tool.'),'Set expectations for a task.'),
lesson('P7.2','Delegating Effectively','Delegando','Delegate ownership, not just tasks.','You need a colleague to lead a workstream.',[["I’d like you to take the lead on…",'Gostaria que você liderasse…'],["You’ll have ownership of…",'Você terá responsabilidade por…']],P('Effective delegation?',['Outcome + ownership + support.','Task with no context.'],0,'Explain authority and support.'),'Delegate a workstream.'),
lesson('P7.3','One-to-One Meetings','Reuniões one-to-one','Run useful development conversations.','You have a weekly one-to-one.',[["What’s going well?",'O que está indo bem?'],["Where do you need support?",'Onde você precisa de apoio?']],P('Good one-to-one is…',['Two-way.','A manager monologue.'],0,'Use questions to surface needs.'),'Open a one-to-one.'),
lesson('P7.4','Coaching Questions','Perguntas de coaching','Help someone think instead of giving every answer.','A team member brings a problem.',[["What options have you considered?",'Que opções você considerou?'],["What would you recommend?",'O que você recomendaria?']],P('Coaching question should…',['Create reflection and ownership.','Provide the answer inside the question.'],0,'Questions can develop autonomy.'),'Ask three coaching questions.'),
lesson('P7.5','Recognition & Motivation','Reconhecimento e motivação','Give meaningful recognition.','A colleague delivered an excellent result.',[["I really appreciated the way you…",'Gostei muito da forma como você…'],["That made a real difference because…",'Isso fez uma diferença real porque…']],P('Strong recognition is…',['Specific about behavior and impact.','Generic praise only.'],0,'Specific recognition is credible.'),'Recognize a colleague.'),
lesson('P7.6','Performance Conversations','Conversas de desempenho','Discuss performance gaps constructively.','Results have been below expectations.',[["There’s a gap between the expected result and…",'Há uma diferença entre o resultado esperado e…'],["What support would help you improve this?",'Que apoio ajudaria você a melhorar isso?']],P('Performance conversation needs…',['Evidence + expectation + plan.','Personal criticism.'],0,'Keep the discussion evidence-based.'),'Address a performance gap.'),
lesson('P7.7','Leading Change','Liderando mudanças','Explain change and create alignment.','Your team is adopting a new process.',[["The reason for this change is…",'O motivo desta mudança é…'],["What this means for the team is…",'O que isso significa para a equipe é…']],P('Change communication should answer…',['Why, what, impact and next step.','Only what.'],0,'People need context and implications.'),'Explain a change to your team.'),
lesson('P7.8','Leading Global Teams','Liderando equipes globais','Create inclusion across locations and cultures.','Some remote team members are less visible.',[["I’d like to make sure everyone has a chance to contribute.",'Gostaria de garantir que todos tenham chance de contribuir.'],["Let’s hear from the remote team as well.",'Vamos ouvir também a equipe remota.']],P('Inclusive leadership behavior?',['Invite distributed voices deliberately.','Wait for the loudest voices.'],0,'Participation often needs facilitation.'),'Invite a remote colleague into the discussion.'),
lesson('P7.9','Leadership Challenge','Desafio de liderança','Lead a high-stakes people conversation.','A strong employee is overloaded and performance is starting to drop.',[["Let’s look at your priorities together.",'Vamos analisar suas prioridades juntos.'],["What can we change to make this sustainable?",'O que podemos mudar para tornar isso sustentável?']],P('Leadership goal?',['Protect performance and person.','Demand more effort only.'],0,'Sustainable performance requires prioritization.'),'Lead the conversation aloud.',12)]},
{id:'P8',order:8,title:'Career Growth & Workplace English',pt:'Crescimento de Carreira e Inglês no Trabalho',goal:'Navigate onboarding, performance, career conversations and professional growth in an international workplace.',achievement:'GLOBAL CAREER BUILDER',lessons:[
lesson('P8.1','Your First Days','Seus primeiros dias','Navigate onboarding confidently.','You have joined an international company.',[["Could you walk me through…?",'Poderia me explicar…?'],["Who should I speak to about…?",'Com quem devo falar sobre…?']],P('Best onboarding behavior?',['Ask targeted questions.','Pretend to understand everything.'],0,'Clarification accelerates integration.'),'Ask three onboarding questions.'),
lesson('P8.2','Understanding Your Role','Entendendo sua função','Clarify responsibilities and priorities.','Your job description is broad.',[["What would you say are my top priorities?",'Quais diria que são minhas principais prioridades?'],["How will success be measured?",'Como o sucesso será medido?']],P('Important role question?',['How is success measured?','Where is the coffee?'],0,'Understand outcomes, not only tasks.'),'Clarify your first 90-day priorities.'),
lesson('P8.3','Building Visibility','Construindo visibilidade','Communicate contributions without sounding boastful.','Your manager may not see all your work.',[["A quick update on what we’ve achieved…",'Uma atualização rápida sobre o que alcançamos…'],["One result I’d highlight is…",'Um resultado que eu destacaria é…']],P('Healthy visibility is…',['Evidence-based communication of impact.','Constant self-promotion.'],0,'Make contributions visible through outcomes.'),'Share a concise achievement update.'),
lesson('P8.4','Performance Reviews','Avaliações de desempenho','Discuss achievements and development professionally.','Your annual review is approaching.',[["One achievement I’m particularly proud of is…",'Uma conquista da qual tenho especial orgulho é…'],["An area I’d like to develop further is…",'Uma área que gostaria de desenvolver mais é…']],P('Balanced review language?',['Achievement + evidence + development.','Only praise.'],0,'Show performance and growth mindset.'),'Prepare two achievements and one development goal.'),
lesson('P8.5','Career Development Conversations','Conversas sobre carreira','Discuss future goals with your manager.','You want broader responsibilities.',[["I’d like to discuss my next development step.",'Gostaria de discutir meu próximo passo de desenvolvimento.'],["What would I need to demonstrate to…?",'O que eu precisaria demonstrar para…?']],P('Strong career question?',['What capabilities should I demonstrate?','When will you promote me?'],0,'Turn ambition into development criteria.'),'Open a career-growth conversation.'),
lesson('P8.6','Promotion & New Responsibilities','Promoção e novas responsabilidades','Discuss readiness for a bigger role.','A new position may open.',[["I believe I’m ready to take on broader responsibility.",'Acredito estar pronto para assumir maior responsabilidade.'],["Over the past year, I’ve…",'No último ano, eu…']],P('Promotion case should rely on…',['Evidence and readiness.','Seniority alone.'],0,'Connect track record to future scope.'),'Make a short promotion case.'),
lesson('P8.7','Remote Work & Flexibility','Trabalho remoto e flexibilidade','Discuss work arrangements professionally.','You want to request a flexible arrangement.',[["I’d like to discuss a flexible working arrangement.",'Gostaria de discutir um regime de trabalho flexível.'],["I can ensure coverage by…",'Posso garantir cobertura por…']],P('Strong request includes…',['Business impact and solution.','Preference only.'],0,'Address how the work will still succeed.'),'Request a flexible arrangement.'),
lesson('P8.8','Career Transition','Transição de carreira','Communicate a professional transition positively.','You are moving to a different role or field.',[["I’m looking to build on my experience in…",'Quero aproveitar minha experiência em…'],["The common thread in my career has been…",'O fio condutor da minha carreira tem sido…']],P('Career-transition story should emphasize…',['Transferable value.','Apology for changing.'],0,'Connect past experience to future contribution.'),'Explain a career transition.'),
lesson('P8.9','Global Career Challenge','Desafio de carreira global','Present your current value and next career direction.','You are discussing your future with an international leader.',[["My next goal is to…",'Meu próximo objetivo é…'],["To prepare for that, I’m currently…",'Para me preparar, atualmente estou…']],P('Strong career narrative connects…',['Past evidence → current value → future direction.','Job titles only.'],0,'Career communication needs a coherent story.'),'Deliver a 90-second career narrative.',12)]}
];
Deno.serve((req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});const u=new URL(req.url),id=u.searchParams.get('module'),lid=u.searchParams.get('lesson');let data;if(lid){const m=modules.find(m=>m.lessons.some(l=>l.id===lid));data=m?.lessons.find(l=>l.id===lid)||null}else if(id)data=modules.find(m=>m.id===id)||null;else data=modules.map(({lessons,...m})=>({...m,lessonCount:lessons.length,status:'premium_ready'}));const lessonCount=modules.reduce((a,m)=>a+m.lessons.length,0);return new Response(JSON.stringify({ok:!!data,version:1,tier:'PREMIUM',pack:'Global Career & Professional Communication',moduleCount:modules.length,lessonCount,finalAchievement:'GLOBAL BUSINESS PROFESSIONAL',data}),{headers:H,status:data?200:404})});
